### ISSUE TITLE
ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#770] opened 2020-06-17 08:49 UTC
Hello temBoard Team

whenever I click in the UI on "Status / Rollbacked transactions", I see the following error message in the temboard.log file.

```
2020-06-17 10:27:26,517 temboardui[25561]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2020-06-17 10:27:26,518 temboardui[25561]: [alerting] ERROR: Postgres output is: '\\N\n'
```

Best regards
William

**Comment by bersace** [comment] 2020-06-17 09:12
Hi @wsescu I can't reproduce this. Can you give some informations about the instance ? How long was it registered ? Do you have this on any agent ? Waht version of PostgreSQL is hosting temBoard repository ? Thanks.

**Comment by wsescu** [comment] 2020-06-17 09:16
It affects the temBoard monitoring instance itself, which is running PostgreSQL version 12.3
temBoard is 6.1 and the Agent is 6.0
I can reproduce this issue any time.

```
$ temboard --version
 INFO: Starting temboard 6.1.
temBoard 6.1
System Red Hat Enterprise Linux Server 7.8 (Maipo)
Python 2.7.5 (/usr/bin/python)
psycopg2 2.5.1 (dt dec pq3 ext)
Tornado 4.2.1
SQLAlchemy 0.9.8
alembic 0.8.3

$ temboard-agent --version
 INFO: Starting temboard-agent 6.0.
6.0
```

**Comment by wsescu** [comment] 2020-06-17 09:18
The instance is registered at least since 9 months. Since I started with temBoard, which is a very cool product, by the way.

**Comment by bersace** [comment] 2020-06-17 09:22
Thanks @wsescu  :-)

What is the content of `monitoring.state_changes` table in temBoard repository ?

**Comment by wsescu** [comment] 2020-06-17 09:26
The state_changes table has currently 32148 rows. Is there anything specific I should look for?

(postgres@[local]:58888)[temboard]> select count(*) from monitoring.state_changes;
 count
-------
 32148
(1 row)

**Comment by bersace** [comment] 2020-06-17 09:28
@wsescu can you post here logs from `GET /server/...` line up to error ?

**Comment by wsescu** [comment] 2020-06-17 09:33
Sure, here is the part of the log. (I have changed the hostname and IP in the log)

```
2020-06-17 10:49:58,785 temboardui[25561]: [access] INFO: 200 GET /server/mon.company.ch/48888/alerting/check_changes/rollback_db.json?start=2020-06-16T08%3A49%3A58.563Z&end=2020-06-17T08%3A49%3A58.565Z&noerror=1 (1.1.1.1) 21.83ms
2020-06-17 10:49:58,786 temboardui[25561]: [access] INFO: 200 GET /server/mon.company.ch/48888/alerting/state_changes/rollback_db.json?key=temboard&start=2020-06-16T08%3A49%3A58.563Z&end=2020-06-17T08%3A49%3A58.565Z&noerror=1 (1.1.1.1) 24.08ms
2020-06-17 10:49:58,822 temboardui[25561]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2020-06-17 10:49:58,822 temboardui[25561]: [alerting] ERROR: Postgres output is: '\\N\n'
2020-06-17 10:49:58,822 temboardui[25561]: [access] INFO: 200 GET /server/mon.company.ch/48888/alerting/check_changes/rollback_db.json?start=2020-06-16T08%3A49%3A58.563Z&end=2020-06-17T08%3A49%3A58.565Z&noerror=1 (1.1.1.1) 21.60ms
2020-06-17 10:49:58,823 temboardui[25561]: [access] INFO: 200 GET /server/mon.company.ch/48888/alerting/state_changes/rollback_db.json?key=postgres&start=2020-06-16T08%3A49%3A58.563Z&end=2020-06-17T08%3A49%3A58.565Z&noerror=1 (1.1.1.1) 24.22ms
```

**Comment by bersace** [comment] 2020-06-17 10:01
@wsescu Please adapt the following query and post the output :

`mon.company.ch` should be good. But 5432 may change.

``` sql
SELECT h.host_id, i.instance_id, monitoring.get_state_changes(
  h.host_id, instance_id, 'rollback_db', 'temboard',
  '2020-06-16T08:49:58.563Z', '2020-06-17T08:49:58.565Z'
)
FROM (SELECT 'mon.company.ch' AS hostname, 5432 AS port) AS query
JOIN monitoring.hosts AS h ON h.hostname = query.hostname
JOIN monitoring.instances AS i ON i.host_id = h.host_id AND i.port = query.port
;
```

**Comment by wsescu** [comment] 2020-06-17 10:11
The quey returned 0 rows. ( I have adapted the host and port beforehand)

```
(postgres@[local]:58888)[temboard]> SELECT h.host_id, i.instance_id, monitoring.get_state_changes(
>   h.host_id, instance_id, 'rollback_db', 'temboard',
>   '2020-06-16T08:49:58.563Z', '2020-06-17T08:49:58.565Z'
> )
> FROM (SELECT 'mon.company.ch' AS hostname, 5432 AS port) AS query
> JOIN monitoring.hosts AS h ON h.hostname = query.hostname
> JOIN monitoring.instances AS i ON i.host_id = h.host_id AND i.port = query.port
> ;
 host_id | instance_id | get_state_changes
---------+-------------+-------------------
(0 rows)

```

**Comment by wsescu** [comment] 2020-06-17 10:23
If I go back in time from 01 January until now, I do get 154 rows

```
(postgres@[local]:58888)[temboard]> SELECT h.host_id, i.instance_id, monitoring.get_state_changes(
>   h.host_id, instance_id, 'rollback_db', 'temboard',
>   '2020-01-01T08:49:58.563Z', '2020-06-17T08:49:58.565Z'
> )
> FROM (SELECT 'mon.company.ch' AS hostname, 5432AS port) AS query
> JOIN monitoring.hosts AS h ON h.hostname = query.hostname
> JOIN monitoring.instances AS i ON i.host_id = h.host_id AND i.port = query.port
> ;
 host_id | instance_id |                      get_state_changes
---------+-------------+--------------------------------------------------------------
       2 |           4 | ("2020-06-15 17:52:41+02",56,CRITICAL,temboard,1781,512,698)
       2 |           4 | ("2020-06-15 17:47:39+02",56,WARNING,temboard,632,512,698)
       2 |           4 | ("2020-06-15 17:42:38+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-15 14:52:01+02",56,CRITICAL,temboard,1932,512,698)
       2 |           4 | ("2020-06-15 13:44:10+02",56,OK,temboard,0,512,698)
       2 |           4 | ("2020-06-15 11:30:28+02",56,CRITICAL,temboard,721,512,698)
       2 |           4 | ("2020-06-15 11:25:26+02",56,OK,temboard,204,512,698)
       2 |           4 | ("2020-06-15 08:34:50+02",56,CRITICAL,temboard,1776,512,698)
       2 |           4 | ("2020-06-15 08:29:48+02",56,OK,temboard,274,512,698)
       2 |           4 | ("2020-06-15 05:34:11+02",56,CRITICAL,temboard,2035,512,698)
       2 |           4 | ("2020-06-15 05:29:09+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-15 02:33:27+02",56,CRITICAL,temboard,1834,512,698)
       2 |           4 | ("2020-06-15 02:28:27+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-14 23:32:50+02",56,CRITICAL,temboard,1482,512,698)
       2 |           4 | ("2020-06-14 23:27:48+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-14 20:32:13+02",56,CRITICAL,temboard,1357,512,698)
       2 |           4 | ("2020-06-14 20:27:10+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-14 17:31:31+02",56,CRITICAL,temboard,1335,512,698)
       2 |           4 | ("2020-06-14 17:26:30+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-14 14:30:50+02",56,CRITICAL,temboard,984,512,698)
       2 |           4 | ("2020-06-14 14:25:49+02",56,OK,temboard,126,512,698)
       2 |           4 | ("2020-06-14 11:35:12+02",56,CRITICAL,temboard,1783,512,698)
       2 |           4 | ("2020-06-14 11:30:10+02",56,WARNING,temboard,617,512,698)
       2 |           4 | ("2020-06-14 11:25:10+02",56,OK,temboard,339,512,698)
       2 |           4 | ("2020-06-14 08:34:35+02",56,CRITICAL,temboard,1782,512,698)
       2 |           4 | ("2020-06-14 08:24:33+02",56,WARNING,temboard,606,512,698)
       2 |           4 | ("2020-06-14 05:33:57+02",56,CRITICAL,temboard,1784,512,698)
       2 |           4 | ("2020-06-14 05:28:56+02",56,WARNING,temboard,625,512,698)
       2 |           4 | ("2020-06-14 02:33:19+02",56,CRITICAL,temboard,1794,512,698)
       2 |           4 | ("2020-06-14 02:28:18+02",56,OK,temboard,271,512,698)
       2 |           4 | ("2020-06-13 23:32:39+02",56,CRITICAL,temboard,2043,512,698)
       2 |           4 | ("2020-06-13 23:27:38+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-13 20:32:02+02",56,CRITICAL,temboard,1691,512,698)
       2 |           4 | ("2020-06-13 20:27:02+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-13 17:31:27+02",56,CRITICAL,temboard,1328,512,698)
       2 |           4 | ("2020-06-13 17:26:26+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-13 14:30:50+02",56,CRITICAL,temboard,1321,512,698)
       2 |           4 | ("2020-06-13 14:25:48+02",56,OK,temboard,231,512,698)
       2 |           4 | ("2020-06-13 11:30:13+02",56,CRITICAL,temboard,1086,512,698)
       2 |           4 | ("2020-06-13 11:25:11+02",56,WARNING,temboard,612,512,698)
       2 |           4 | ("2020-06-13 08:29:33+02",56,CRITICAL,temboard,732,512,698)
       2 |           4 | ("2020-06-13 08:24:33+02",56,WARNING,temboard,679,512,698)
       2 |           4 | ("2020-06-13 02:33:14+02",56,CRITICAL,temboard,1786,512,698)
       2 |           4 | ("2020-06-13 02:28:13+02",56,WARNING,temboard,619,512,698)
       2 |           4 | ("2020-06-12 23:32:37+02",56,CRITICAL,temboard,1770,512,698)
       2 |           4 | ("2020-06-12 23:27:35+02",56,OK,temboard,274,512,698)
       2 |           4 | ("2020-06-12 20:31:57+02",56,CRITICAL,temboard,1778,512,698)
       2 |           4 | ("2020-06-12 20:26:59+02",56,OK,temboard,226,512,698)
       2 |           4 | ("2020-06-12 17:31:18+02",56,CRITICAL,temboard,1851,512,698)
       2 |           4 | ("2020-06-12 17:26:16+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-12 14:30:38+02",56,CRITICAL,temboard,1594,512,698)
       2 |           4 | ("2020-06-12 14:25:37+02",56,OK,temboard,117,512,698)
       2 |           4 | ("2020-06-12 11:30:00+02",56,CRITICAL,temboard,1492,512,698)
       2 |           4 | ("2020-06-12 11:24:57+02",56,OK,temboard,240,512,698)
       2 |           4 | ("2020-06-12 08:29:18+02",56,CRITICAL,temboard,1342,512,698)
       2 |           4 | ("2020-06-12 08:24:17+02",56,WARNING,temboard,620,512,698)
       2 |           4 | ("2020-06-11 23:32:24+02",56,CRITICAL,temboard,1783,512,698)
       2 |           4 | ("2020-06-11 23:27:23+02",56,WARNING,temboard,612,512,698)
       2 |           4 | ("2020-06-11 20:31:48+02",56,CRITICAL,temboard,1770,512,698)
       2 |           4 | ("2020-06-11 20:26:47+02",56,OK,temboard,280,512,698)
       2 |           4 | ("2020-06-11 17:31:08+02",56,CRITICAL,temboard,1682,512,698)
       2 |           4 | ("2020-06-11 17:26:08+02",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-06-11 14:30:29+02",56,CRITICAL,temboard,1915,512,698)
       2 |           4 | ("2020-06-11 14:25:27+02",56,OK,temboard,120,512,698)
       2 |           4 | ("2020-06-11 11:29:48+02",56,CRITICAL,temboard,1702,512,698)
       2 |           4 | ("2020-06-11 11:24:47+02",56,WARNING,temboard,604,512,698)
       2 |           4 | ("2020-06-10 17:31:01+02",56,CRITICAL,temboard,1782,512,698)
       2 |           4 | ("2020-06-10 17:26:00+02",56,WARNING,temboard,632,512,698)
       2 |           4 | ("2020-06-10 14:30:23+02",56,CRITICAL,temboard,1794,512,698)
       2 |           4 | ("2020-06-10 14:25:23+02",56,OK,temboard,412,512,698)
       2 |           4 | ("2020-06-10 11:29:45+02",56,CRITICAL,temboard,1940,512,698)
       2 |           4 | ("2020-06-10 11:24:49+02",56,OK,temboard,216,512,698)
       2 |           4 | ("2020-06-10 08:29:06+02",56,CRITICAL,temboard,1698,512,698)
       2 |           4 | ("2020-06-10 08:24:04+02",56,WARNING,temboard,617,512,698)
       2 |           4 | ("2020-05-08 11:29:26+02",56,CRITICAL,temboard,1587,512,698)
       2 |           4 | ("2020-05-08 11:24:26+02",56,WARNING,temboard,561,512,698)
       2 |           4 | ("2020-05-08 11:19:24+02",56,OK,temboard,44,512,698)
       2 |           4 | ("2020-04-29 08:32:15+02",56,CRITICAL,temboard,1428,512,698)
       2 |           4 | ("2020-04-29 08:22:12+02",56,OK,temboard,398,512,698)
       2 |           4 | ("2020-04-20 08:36:49+02",56,CRITICAL,temboard,1620,512,698)
       2 |           4 | ("2020-04-17 14:31:04+02",56,OK,temboard,239,512,698)
       2 |           4 | ("2020-04-17 14:26:03+02",56,WARNING,temboard,551,512,698)
       2 |           4 | ("2020-04-17 14:16:02+02",56,OK,temboard,225,512,698)
       2 |           4 | ("2020-04-17 14:11:01+02",56,CRITICAL,temboard,736,512,698)
       2 |           4 | ("2020-03-13 08:22:18+01",56,OK,temboard,452,512,698)
       2 |           4 | ("2020-03-13 08:12:17+01",56,CRITICAL,temboard,888,512,698)
       2 |           4 | ("2020-03-07 08:20:16+01",56,OK,temboard,237,512,698)
       2 |           4 | ("2020-03-07 08:10:14+01",56,WARNING,temboard,525,512,698)
       2 |           4 | ("2020-02-14 13:04:33+01",56,OK,temboard,378,512,698)
       2 |           4 | ("2020-02-14 12:59:32+01",56,WARNING,temboard,528,512,698)
       2 |           4 | ("2020-02-12 11:06:38+01",56,OK,temboard,201,512,698)
       2 |           4 | ("2020-02-12 11:01:37+01",56,CRITICAL,temboard,764,512,698)
       2 |           4 | ("2020-02-12 10:56:37+01",56,WARNING,temboard,644,512,698)
       2 |           4 | ("2020-02-12 10:51:36+01",56,CRITICAL,temboard,1058,512,698)
       2 |           4 | ("2020-02-12 10:46:35+01",56,OK,temboard,15,512,698)
       2 |           4 | ("2020-02-12 10:36:35+01",56,OK,temboard,0,512,698)
       2 |           4 | ("2020-02-12 10:06:31+01",56,CRITICAL,temboard,2196,512,698)
       2 |           4 | ("2020-02-12 10:01:30+01",56,CRITICAL,temboard,1032,512,698)
       2 |           4 | ("2020-02-12 09:56:30+01",56,OK,temboard,212,512,698)
       2 |           4 | ("2020-02-12 09:36:28+01",56,CRITICAL,temboard,1023,512,698)
       2 |           4 | ("2020-02-12 09:31:28+01",56,OK,temboard,0,512,698)
       2 |           4 | ("2020-02-12 09:26:28+01",56,CRITICAL,temboard,2298,512,698)
       2 |           4 | ("2020-01-17 14:37:51+01",56,OK,temboard,157,512,698)
       2 |           4 | ("2020-01-17 14:36:50+01",56,CRITICAL,temboard,778,512,698)
       2 |           4 | ("2020-01-13 13:11:56+01",56,OK,temboard,147,512,698)
       2 |           4 | ("2020-01-13 13:10:55+01",56,WARNING,temboard,592,512,698)
       2 |           4 | ("2020-01-07 12:42:28+01",56,OK,temboard,277,378,512)
       2 |           4 | ("2020-01-07 12:41:28+01",56,WARNING,temboard,436,378,512)
       2 |           4 | ("2020-01-07 09:42:05+01",56,OK,temboard,333,378,512)
       2 |           4 | ("2020-01-07 09:41:04+01",56,WARNING,temboard,444,378,512)
       2 |           4 | ("2020-01-07 06:41:40+01",56,OK,temboard,376,378,512)
       2 |           4 | ("2020-01-07 06:40:40+01",56,WARNING,temboard,434,378,512)
       2 |           4 | ("2020-01-07 06:39:39+01",56,OK,temboard,5,378,512)
       2 |           4 | ("2020-01-07 03:42:16+01",56,OK,temboard,243,378,512)
       2 |           4 | ("2020-01-07 03:41:16+01",56,WARNING,temboard,408,378,512)
       2 |           4 | ("2020-01-07 00:41:54+01",56,OK,temboard,356,378,512)
       2 |           4 | ("2020-01-07 00:40:53+01",56,WARNING,temboard,414,378,512)
       2 |           4 | ("2020-01-07 00:39:53+01",56,OK,temboard,171,378,512)
       2 |           4 | ("2020-01-06 21:41:28+01",56,OK,temboard,342,378,512)
       2 |           4 | ("2020-01-06 21:40:27+01",56,WARNING,temboard,414,378,512)
       2 |           4 | ("2020-01-06 21:39:27+01",56,OK,temboard,17,378,512)
       2 |           4 | ("2020-01-06 18:42:03+01",56,OK,temboard,247,378,512)
       2 |           4 | ("2020-01-06 18:41:03+01",56,WARNING,temboard,410,378,512)
       2 |           4 | ("2020-01-06 15:41:39+01",56,OK,temboard,217,378,512)
       2 |           4 | ("2020-01-06 15:40:39+01",56,WARNING,temboard,416,378,512)
       2 |           4 | ("2020-01-06 12:41:14+01",56,OK,temboard,141,378,512)
       2 |           4 | ("2020-01-06 12:40:14+01",56,WARNING,temboard,444,378,512)
       2 |           4 | ("2020-01-06 09:41:50+01",56,OK,temboard,203,378,512)
       2 |           4 | ("2020-01-06 09:40:50+01",56,WARNING,temboard,422,378,512)
       2 |           4 | ("2020-01-06 06:41:24+01",56,OK,temboard,197,378,512)
       2 |           4 | ("2020-01-06 06:40:24+01",56,WARNING,temboard,440,378,512)
       2 |           4 | ("2020-01-06 03:40:58+01",56,OK,temboard,285,378,512)
       2 |           4 | ("2020-01-06 03:39:58+01",56,WARNING,temboard,426,378,512)
       2 |           4 | ("2020-01-06 00:40:34+01",56,OK,temboard,339,378,512)
       2 |           4 | ("2020-01-06 00:39:34+01",56,WARNING,temboard,416,378,512)
       2 |           4 | ("2020-01-06 00:38:33+01",56,OK,temboard,5,378,512)
       2 |           4 | ("2020-01-05 21:41:09+01",56,OK,temboard,199,378,512)
       2 |           4 | ("2020-01-05 21:40:08+01",56,WARNING,temboard,410,378,512)
       2 |           4 | ("2020-01-05 18:40:42+01",56,OK,temboard,249,378,512)
       2 |           4 | ("2020-01-05 18:39:42+01",56,WARNING,temboard,408,378,512)
       2 |           4 | ("2020-01-05 15:40:17+01",56,OK,temboard,255,378,512)
       2 |           4 | ("2020-01-05 15:39:17+01",56,WARNING,temboard,406,378,512)
       2 |           4 | ("2020-01-05 09:40:29+01",56,OK,temboard,193,378,512)
       2 |           4 | ("2020-01-05 09:39:29+01",56,WARNING,temboard,408,378,512)
       2 |           4 | ("2020-01-05 06:40:04+01",56,OK,temboard,166,378,512)
       2 |           4 | ("2020-01-05 06:39:03+01",56,WARNING,temboard,405,378,512)
       2 |           4 | ("2020-01-05 03:39:42+01",56,OK,temboard,217,378,512)
       2 |           4 | ("2020-01-05 03:38:41+01",56,WARNING,temboard,416,378,512)
       2 |           4 | ("2020-01-05 00:39:18+01",56,OK,temboard,138,378,512)
       2 |           4 | ("2020-01-05 00:38:17+01",56,WARNING,temboard,403,378,512)
       2 |           4 | ("2020-01-04 12:38:51+01",56,OK,temboard,138,378,512)
       2 |           4 | ("2020-01-04 12:37:51+01",56,WARNING,temboard,407,378,512)
       2 |           4 | ("2020-01-04 00:38:24+01",56,OK,temboard,131,378,512)
       2 |           4 | ("2020-01-04 00:37:24+01",56,WARNING,temboard,380,378,512)
(154 rows)

```

**Comment by bersace** [comment] 2020-06-17 10:26
What is the output of (please adapt hostname and port lines)

``` sql
SELECT h.host_id, i.instance_id, c.check_id, sc."key", sc.datetime, sc."state", sc.value
FROM (SELECT
  'repository.fqdn' AS hostname,
  5432 AS port,
  'rollback_db' AS "name",
  'temboard' AS "key",
  '2020-06-16T08:49:58.563Z'::TIMESTAMPTZ AS "start",
  '2020-06-17T08:49:58.565Z'::TIMESTAMPTZ AS "end"
) AS query
LEFT OUTER JOIN monitoring.hosts AS h ON h.hostname = query.hostname
LEFT OUTER JOIN monitoring.instances AS i ON i.host_id = h.host_id AND i.port = query.port
LEFT OUTER JOIN monitoring.checks AS c
  ON c.host_id = h.host_id AND c.instance_id = i.instance_id AND c.name = query.name
LEFT OUTER JOIN monitoring.state_changes AS sc
  ON sc.check_id = c.check_id AND sc."key" = query."key" AND sc.datetime <@ tstzrange(query.start, query.end)
;
```

**Comment by wsescu** [comment] 2020-06-17 10:26
From my point of view, the temBoard instance has a lot of rollbacked transactions anyway. I have already increased the thresholds to 512/698, which is very high.

![image](https://user-images.githubusercontent.com/54099545/84887142-a39fdc80-b095-11ea-8cd3-10fcd17ec180.png)

**Comment by bersace** [comment] 2020-06-17 10:29
I'm not sure what are these rollback about. I need to add logs about that.

**Comment by bersace** [comment] 2020-06-17 10:33
Ok, i reproduced !! :-)

**Comment by bersace** [comment] 2020-06-17 10:33
Actually, these errors are safe to ignore. It's just means that there is not state changes for the days. We need to chase such false error. Thanks !

**Comment by wsescu** [comment] 2020-10-08 06:32
Dear @bersace 

it looks like, that the huge number of rollbacked session, is related to the following warnings (from temboard.log)

```
2020-10-07 14:19:50,695 temboardui[16419]: [tools] WARNING: Failed to preprocess alerting check 'wal_files_archive': list index out of range
2020-10-07 14:19:50,695 temboardui[16419]: [tools] WARNING: Failed to preprocess alerting check 'wal_files_total': list index out of range
2020-10-07 14:19:50,696 temboardui[16419]: [tools] WARNING: Failed to preprocess alerting check 'replication_lag': list index out of range
2020-10-07 14:19:50,761 temboardui[16374]: [tools] WARNING: Failed to preprocess alerting check 'replication_lag': list index out of range
2020-10-07 14:19:50,761 temboardui[16374]: [tools] WARNING: Failed to preprocess alerting check 'replication_connection': list index out of range
```

Whenever such a warning shows up, I do get immediately the EOF in the postgresql.log file.

```
2020-10-07 14:19:51.223 CEST [16498] LOG:  unexpected EOF on client connection with an open transaction
2020-10-07 14:19:51.233 CEST [16499] LOG:  unexpected EOF on client connection with an open transaction
2020-10-07 14:19:51.240 CEST [16481] LOG:  unexpected EOF on client connection with an open transaction
2020-10-07 14:19:51.253 CEST [16486] LOG:  unexpected EOF on client connection with an open transaction
2020-10-07 14:19:51.259 CEST [16503] LOG:  unexpected EOF on client connection with an open transaction
2020-10-07 14:19:51.297 CEST [16504] LOG:  unexpected EOF on client connection with an open transaction
```

Is there any way to fix this issue? The problem is that I have so many EOF messages in the postgresql.log file, so that it
becomes unreadable.

Cheers
William

**Comment by bersace** [comment] 2020-10-08 12:38
@wsescu thanks for the investigation. I proposed a patch at #868 . Is it possible for you to test it ?

**Comment by wsescu** [comment] 2020-10-08 12:42
@bersace 

sure, I can test it, but I need a new temboard rpm to do so

**Comment by wsescu** [comment] 2020-10-16 06:55
Dear @bersace 

thanks for the new 7.3 rpm. 

I have tried it out this morning, however, the issue still remains.

```
$ temboard-migratedb upgrade
 INFO: Starting temboard-migratedb 7.3.
 INFO: Found config file /etc/temboard/temboard.conf.
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Database up to date.
```
![image](https://user-images.githubusercontent.com/54099545/96222668-faa6b700-0f8c-11eb-9fc4-9803a3b4f610.png)


The rollbacks still correlate with the following Warnings:

```
2020-10-16 08:15:39,119 temboardui[20990]: [tools] WARNING: Failed to preprocess alerting check 'wal_files_archive': list index out of range
2020-10-16 08:15:39,119 temboardui[20990]: [tools] WARNING: Failed to preprocess alerting check 'wal_files_total': list index out of range
2020-10-16 08:15:39,119 temboardui[20990]: [tools] WARNING: Failed to preprocess alerting check 'replication_lag': list index out of range
2020-10-16 08:15:39,136 temboardui[21000]: [tools] WARNING: Failed to preprocess alerting check 'wal_files_archive': list index out of range
2020-10-16 08:15:39,136 temboardui[21000]: [tools] WARNING: Failed to preprocess alerting check 'wal_files_total': list index out of range
2020-10-16 08:15:39,136 temboardui[21000]: [tools] WARNING: Failed to preprocess alerting check 'replication_lag': list index out of range
```

Cheers
William

**Comment by bersace** [comment] 2020-10-16 07:09
Hi @wsescu thanks for the feedback. We'll have to reproduce this one too. Did you restart temBoard ?

**Comment by wsescu** [comment] 2020-10-16 08:09
Sure. I did the restart of the temBoard server. However, the issue still remains.

**Comment by bersace** [comment] 2020-10-16 08:30
@wsescu ok, thanks for the confirmation.

**Comment by pgiraud** [comment] 2020-11-02 07:47
PR #871 fixes the initial issue reported here.

**Comment by wsescu** [comment] 2021-01-03 09:49
Dear @pgiraud 
I have upgrade to temBoard 7.4 and the agent to 7.5, however, the issue is still there.
Cheers
William

**Comment by pgiraud** [comment] 2021-01-04 07:32
@wsescu Can you please elaborate which issue you are refering to? Are you still getting "Failed to parse JSON from Postgres: No JSON object could be decoded" error messages in the logs?

**Comment by wsescu** [comment] 2021-01-04 10:06
Dear @pgiraud 

yes. Both issues still exist. I still do get the ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
Here are the latest ones from this morning.

```
2021-01-04 07:23:17,745 temboardui[30953]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-04 07:23:17,751 temboardui[30953]: [alerting] ERROR: Postgres output is: '\\N\n'
2021-01-04 07:23:17,761 temboardui[30953]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-04 07:23:17,761 temboardui[30953]: [alerting] ERROR: Postgres output is: '\\N\n'
```

And I still do get auf huge number of Rollbacks. I did alread the upgrade to 7.4.

```
$ temboard --version
 INFO: Starting temboard 7.4.
temBoard 7.4
System Red Hat Enterprise Linux Server 7.8 (Maipo)
Python 2.7.5 (/usr/bin/python)
psycopg2 2.5.1 (dt dec pq3 ext)
Tornado 4.2.1
SQLAlchemy 0.9.8
alembic 0.8.3
```

Cheers
William

**Comment by wsescu** [comment] 2021-01-12 12:40
Dear @pgiraud 

reproducing the JSON error is quite easy. By just clicking on the "Rollbacked transactions" buttion. (on any instance)

![image](https://user-images.githubusercontent.com/54099545/104315504-5a085a80-54db-11eb-8b35-762fb59fc107.png)

Then you will find in the temboard.log of the server the following parsing JSON errors:


```
2021-01-12 13:33:52,727 temboardui[1249]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-12 13:33:52,727 temboardui[1249]: [alerting] ERROR: Postgres output is: '\\N\n'
2021-01-12 13:33:52,727 temboardui[1249]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-12 13:33:52,728 temboardui[1249]: [alerting] ERROR: Postgres output is: '\\N\n'
2021-01-12 13:33:52,728 temboardui[1249]: [access] INFO: 200 GET /server/hostname/44444/alerting/state_changes/rollback_db.json?key=barman&start=2021-01-11T12%3A33%3A52.175Z&end=2021-01-12T12%3A33%3A52.175Z&noerror=1 (10.50.241.85) 26.52ms
2021-01-12 13:33:52,729 temboardui[1249]: [access] INFO: 200 GET /server/hostname/44444/alerting/check_changes/rollback_db.json?start=2021-01-11T12%3A33%3A52.175Z&end=2021-01-12T12%3A33%3A52.175Z&noerror=1 (10.50.241.85) 24.64ms
2021-01-12 13:33:52,861 temboardui[1249]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-12 13:33:52,861 temboardui[1249]: [alerting] ERROR: Postgres output is: '\\N\n'
2021-01-12 13:33:52,862 temboardui[1249]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-12 13:33:52,862 temboardui[1249]: [alerting] ERROR: Postgres output is: '\\N\n'
2021-01-12 13:33:52,863 temboardui[1249]: [access] INFO: 200 GET /server/hostname/44444/alerting/check_changes/rollback_db.json?start=2021-01-11T12%3A33%3A52.175Z&end=2021-01-12T12%3A33%3A52.175Z&noerror=1 (10.50.241.85) 23.44ms
2021-01-12 13:33:52,864 temboardui[1249]: [access] INFO: 200 GET /server/hostname/44444/alerting/state_changes/rollback_db.json?key=template1&start=2021-01-11T12%3A33%3A52.175Z&end=2021-01-12T12%3A33%3A52.175Z&noerror=1 (10.50.241.85) 26.41ms
2021-01-12 13:33:52,961 temboardui[1249]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-12 13:33:52,961 temboardui[1249]: [alerting] ERROR: Postgres output is: '\\N\n'
2021-01-12 13:33:52,962 temboardui[1249]: [access] INFO: 200 GET /server/hostname/44444/alerting/check_changes/rollback_db.json?start=2021-01-11T12%3A33%3A52.175Z&end=2021-01-12T12%3A33%3A52.175Z&noerror=1 (10.50.241.85) 27.13ms
2021-01-12 13:33:52,962 temboardui[1249]: [alerting] ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded
2021-01-12 13:33:52,963 temboardui[1249]: [alerting] ERROR: Postgres output is: '\\N\n'
2021-01-12 13:33:52,964 temboardui[1249]: [access] INFO: 200 GET /server/hostname/44444/alerting/state_changes/rollback_db.json?key=postgres&start=2021-01-11T12%3A33%3A52.175Z&end=2021-01-12T12%3A33%3A52.175Z&noerror=1 (10.50.241.85) 31.19ms
```

Cheers
William

**Comment by pgiraud** [comment] 2021-01-12 12:55
My bad, the fix has been done against the master branch. Thus it has never been added to a 7.x release.

**Comment by pgiraud** [comment] 2021-01-12 13:16
@wsescu May I ask you to install the 7.5 version of temboard UI and see if the issue is fixed?

**Comment by wsescu** [comment] 2021-01-12 13:30
@pgiraud Thank you very much. After upgrading temBoard to version 7.5, the following issue is fixed.

`ERROR: Failed to parse JSON from Postgres: No JSON object could be decoded`

Thanks.

**Comment by pgiraud** [comment] 2021-01-12 13:34
Thanks. I'm closing the current issue then.
For the rollbacks, we have been aware of the problem for a while but we didn't find any way to fix it. See https://github.com/dalibo/temboard/issues/408#issuecomment-482505131

**Closed by pgiraud** 2021-01-12 13:34 UTC
Labels: bug
