### ISSUE TITLE
slow perf since upgrade to temboard 9.0 missing index for monitoring.append_state_changes function

### ISSUE THREAD

**Issue by delattresylvain** [dalibo/temboard#1537] opened 2024-11-05 14:51 UTC
Hi,

Since upgrade to temboard 9.0 i'm having a performance issue / huge load on temboard central

After investigations i found that the select on monitoring.state_changes called by the monitoring.append_state_changes function is the most called.

The average time is not so long but this function is called a million of times.

So i added an index with a huge time benefit:

temboard=# explain (analyze,buffers) SELECT *        FROM monitoring.state_changes WHERE check_id = **** AND key = '********' ORDER BY datetime DESC LIMIT 50;
                                                                 QUERY PLAN                                                                 
--------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=46243.30..46247.74 rows=38 width=40) (actual time=143.522..145.625 rows=50 loops=1)
   Buffers: shared hit=141 read=26405
   ->  Gather Merge  (cost=46243.30..46247.74 rows=38 width=40) (actual time=143.520..145.617 rows=50 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         Buffers: shared hit=141 read=26405
         ->  Sort  (cost=45243.28..45243.33 rows=19 width=40) (actual time=140.098..140.103 rows=40 loops=3)
               Sort Key: datetime DESC
               Sort Method: top-N heapsort  Memory: 32kB
               Buffers: shared hit=141 read=26405
               Worker 0:  Sort Method: top-N heapsort  Memory: 32kB
               Worker 1:  Sort Method: top-N heapsort  Memory: 32kB
               ->  Parallel Seq Scan on state_changes  (cost=0.00..45242.88 rows=19 width=40) (actual time=0.272..139.412 rows=777 loops=3)
                     Filter: ((check_id = ****) AND ((key)::text = '**********'::text))
                     Rows Removed by Filter: 1002253
                     Buffers: shared hit=27 read=26405
 Planning:
   Buffers: shared hit=44 read=1 dirtied=1
 Planning Time: 0.424 ms
 **Execution Time: 145.707 ms**
(20 rows)

temboard=# create index concurrently idx_check_key_datetime on monitoring.state_changes(check_id, key,datetime DESC);
CREATE INDEX
temboard=# explain (analyze,buffers) SELECT *        FROM monitoring.state_changes WHERE check_id = **** AND key = '*************' ORDER BY datetime DESC LIMIT 50;
                                                                   QUERY PLAN                                                                    
-------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.43..167.66 rows=45 width=40) (actual time=0.019..0.182 rows=50 loops=1)
   Buffers: shared hit=24 read=21
   ->  Index Scan using idx_check_key_datetime on state_changes  (cost=0.43..167.66 rows=45 width=40) (actual time=0.018..0.178 rows=50 loops=1)
         Index Cond: ((check_id = ********) AND ((key)::text = '*****************'::text))
         Buffers: shared hit=24 read=21
 Planning:
   Buffers: shared hit=14
 Planning Time: 0.139 ms
 **Execution Time: 0.195 ms**
(9 rows)

Regards,
Sylvain

**Comment by bersace** [comment] 2024-11-05 14:52
Hi, this is duplicate of #1527 , isn't it ?

**Comment by bersace** [comment] 2024-11-05 14:56
How many instances do you manage with temBoard ?

**Comment by bersace** [comment] 2024-11-06 08:43
Closing in favor of #1527

**Closed by bersace** 2024-11-06 08:43 UTC
