### ISSUE TITLE
Automatically update PostgreSQL version after upgrade

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#666] opened 2019-08-14 08:49 UTC
Hello temBoard team

after I have upgraded one PostgreSQL instance from 11.4 to 11.5, temBoard still shows the old version in the gui.

I have adjusted the pg_ctl entry in the Agent temboard-agent.conf file, and restarted the Agent, however, it still shows the old version (11.4). But it should be 11.5.

![image](https://user-images.githubusercontent.com/54099545/63007460-f8286900-be80-11e9-9691-be5622efffc7.png)

I am using temBoard 4.1.

Any help would be very appreciated.

Cheers
William

**Comment by pgiraud** [comment] 2019-08-14 09:17
Unfortunately the instance info are not updated automatically in the UI. These information are stored in the repository database when the instance is registered (manually or automatically). The agent `discover` service is called to get the details about the instance.

As a workaround, what you can do is to go to the instances settings,  clic on the `edit` button and save the settings without any modification. The information for the instance should be discovered once again and any change (version upgrade for example) should be taken into account.

**Comment by wsescu** [comment] 2019-08-14 09:21
Wowwww ... what a fast response. Thank you. Your suggested workaround helped.
However, it would be great if the version would get updated automatically. ;-)

**Comment by pgiraud** [comment] 2020-06-22 06:27
Duplicate of #299. Closing.

**Closed by pgiraud** 2020-06-22 06:27 UTC
Labels: feature request
