### ISSUE TITLE
ERROR: Unhandled error -> After Upgrade from Version 5 to Version 6

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#762] opened 2020-06-15 11:44 UTC
Hello temBoard Team

after upgrading from temBoard Version 5 to Version 6, I do get the following error:

```
2020-06-15 13:36:39,064 temboardui[18890]: [app] INFO: setuptools is too old for plugin hotload.
2020-06-15 13:36:39,064 temboardui[18890]: [app] INFO: If new plugin can't be found, just restart.
2020-06-15 13:36:39,065 temboardui[18890]: [pluginsmgmt] INFO: Loaded plugin 'activity'.
2020-06-15 13:36:39,065 temboardui[18890]: [pluginsmgmt] INFO: Loaded plugin 'dashboard'.
2020-06-15 13:36:39,078 temboardui[18890]: [pluginsmgmt] INFO: Loaded plugin 'monitoring'.
2020-06-15 13:36:39,079 temboardui[18890]: [pluginsmgmt] INFO: Loaded plugin 'pgconf'.
2020-06-15 13:36:39,079 temboardui[18890]: [pluginsmgmt] INFO: Loaded plugin 'maintenance'.
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR: Unhandled error:
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR: Traceback (most recent call last):
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 301, in entrypoint
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     retcode = self.main(argv, environ)
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/__main__.py", line 360, in main
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     check_schema(self.config)
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/__init__.py", line 106, in check_schema
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     script.run_env()
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     util.load_python_file(self.dir, 'env.py')
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     module = load_module_py(module_id, path)
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     mod = imp.load_source(module_id, path, fp)
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 79, in <module>
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     run_migrations_online()
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 73, in run_migrations_online
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     context.run_migrations()
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "<string>", line 8, in run_migrations
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     self.get_context().run_migrations(**kw)
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 303, in run_migrations
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     for step in self._migrations_fn(heads, self):
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/__init__.py", line 88, in fn
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR:     current_obj = next(iter(script.get_all_current(current)))
2020-06-15 13:36:39,113 temboardui[18890]: [app] ERROR: AttributeError: 'ScriptDirectory' object has no attribute 'get_all_current'
2020-06-15 13:36:39,115 temboardui[18890]: [app] ERROR: temboardui version is 6.0.
2020-06-15 13:36:39,115 temboardui[18890]: [app] ERROR: This is a bug!
2020-06-15 13:36:39,115 temboardui[18890]: [app] ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```

Could you please help?

I just followed the upgrade instructions, and now it looks broken.

- Have stopped temBoard

- Run the script: temboard-migratedb stamp (It atuomatically created table alembic_version)

- Started temBoard

Best regards
William

**Comment by pgiraud** [comment] 2020-06-15 11:54
Thanks for report.
Can you please tell us what the following command returns ?
```
temboard --version
```

**Comment by wsescu** [comment] 2020-06-15 11:55
Sure. It is:

$ temboard --version
 INFO: Starting temboard 6.0.
temBoard 6.0
System Red Hat Enterprise Linux Server 7.8 (Maipo)
Python 2.7.5 (/usr/bin/python)
psycopg2 2.5.1 (dt dec pq3 ext)
Tornado 4.2.1
SQLAlchemy 0.9.8
alembic 0.8.3

**Comment by wsescu** [comment] 2020-06-15 11:56
I have observed, that the table alembic_version was created in the public schema. Is that correct?
Shouldn't it be in the "application" schema?

**Comment by pgiraud** [comment] 2020-06-15 11:58
That's correct. The issue is in my opinion related to the version of alembic.

**Comment by wsescu** [comment] 2020-06-15 12:12
I do have alembic version 0.8.3-3.el7

I have upgrade to temBoard 6 with the following command, and alembic was pulled from the EPEL.

Is the alembic version 0.8.3 not the correct one? Which version should I use?

$ sudo yum localupdate temboard-6.0-1.el7.noarch.rpm

Loaded plugins: enabled_repos_upload, langpacks, package_upload, product-id, search-disabled-repos, subscription-manager
Examining temboard-6.0-1.el7.noarch.rpm: temboard-6.0-1.el7.noarch
Marking temboard-6.0-1.el7.noarch.rpm as an update to temboard-5.1-1.el7.noarch
Resolving Dependencies
--> Running transaction check
---> Package temboard.noarch 0:5.1-1.el7 will be updated
---> Package temboard.noarch 0:6.0-1.el7 will be an update
--> Processing Dependency: python-alembic for package: temboard-6.0-1.el7.noarch
epel/x86_64/metalink                                                                                                                                        |  16 kB  00:00:00
epel                                                                                                                                                        | 5.3 kB  00:00:00
rhel-7-server-extras-rpms                                                                                                                                   | 2.0 kB  00:00:00
rhel-7-server-optional-rpms                                                                                                                                 | 2.0 kB  00:00:00
rhel-7-server-rh-common-rpms                                                                                                                                | 2.1 kB  00:00:00
rhel-7-server-rpms                                                                                                                                          | 2.0 kB  00:00:00
rhel-7-server-satellite-tools-6.6-rpms                                                                                                                      | 2.1 kB  00:00:00
rhel-7-server-supplementary-rpms                                                                                                                            | 2.3 kB  00:00:00
rhel-server-rhscl-7-rpms                                                                                                                                    | 2.3 kB  00:00:00
(1/3): epel/x86_64/group_gz                                                                                                                                 |  95 kB  00:00:00
(2/3): epel/x86_64/updateinfo                                                                                                                               | 1.0 MB  00:00:00
(3/3): epel/x86_64/primary_db                                                                                                                               | 6.8 MB  00:00:00
--> Running transaction check
---> Package python-alembic.noarch 0:0.8.3-3.el7 will be installed
--> Processing Dependency: python-editor for package: python-alembic-0.8.3-3.el7.noarch
--> Processing Dependency: python-mako for package: python-alembic-0.8.3-3.el7.noarch
--> Running transaction check
---> Package python-editor.noarch 0:0.4-4.el7 will be installed
---> Package python-mako.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python-markupsafe for package: python-mako-0.8.1-2.el7.noarch
--> Processing Dependency: python-beaker for package: python-mako-0.8.1-2.el7.noarch
--> Running transaction check
---> Package python-beaker.noarch 0:1.5.4-10.el7 will be installed
--> Processing Dependency: python-paste for package: python-beaker-1.5.4-10.el7.noarch
---> Package python-markupsafe.x86_64 0:0.11-10.el7 will be installed
--> Running transaction check
---> Package python-paste.noarch 0:1.7.5.1-9.20111221hg1498.el7 will be installed
--> Processing Dependency: python-tempita for package: python-paste-1.7.5.1-9.20111221hg1498.el7.noarch
--> Running transaction check
---> Package python-tempita.noarch 0:0.5.1-6.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================================================
 Package                                 Arch                         Version                                               Repository                                        Size
===================================================================================================================================================================================
Updating:
 temboard                                noarch                       6.0-1.el7                                             /temboard-6.0-1.el7.noarch                       3.3 M
Installing for dependencies:
 python-alembic                          noarch                       0.8.3-3.el7                                           epel                                             716 k
 python-beaker                           noarch                       1.5.4-10.el7                                          rhel-7-server-rpms                                80 k
 python-editor                           noarch                       0.4-4.el7                                             epel                                              13 k
 python-mako                             noarch                       0.8.1-2.el7                                           rhel-7-server-rpms                               307 k
 python-markupsafe                       x86_64                       0.11-10.el7                                           rhel-7-server-rpms                                25 k
 python-paste                            noarch                       1.7.5.1-9.20111221hg1498.el7                          rhel-7-server-rpms                               866 k
 python-tempita                          noarch                       0.5.1-6.el7                                           rhel-7-server-rpms                                33 k

Transaction Summary
===================================================================================================================================================================================
Install             ( 7 Dependent packages)
Upgrade  1 Package

Total size: 5.3 M
Total download size: 2.0 M
Is this ok [y/d/N]: y
Downloading packages:
(1/7): python-beaker-1.5.4-10.el7.noarch.rpm                                                                                                                |  80 kB  00:00:00
(2/7): python-alembic-0.8.3-3.el7.noarch.rpm                                                                                                                | 716 kB  00:00:00
(3/7): python-editor-0.4-4.el7.noarch.rpm                                                                                                                   |  13 kB  00:00:00
(4/7): python-mako-0.8.1-2.el7.noarch.rpm                                                                                                                   | 307 kB  00:00:00
(5/7): python-markupsafe-0.11-10.el7.x86_64.rpm                                                                                                             |  25 kB  00:00:00
(6/7): python-paste-1.7.5.1-9.20111221hg1498.el7.noarch.rpm                                                                                                 | 866 kB  00:00:00
(7/7): python-tempita-0.5.1-6.el7.noarch.rpm                                                                                                                |  33 kB  00:00:00
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                              2.1 MB/s | 2.0 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : python-editor-0.4-4.el7.noarch                                                                                                                                  1/9
  Installing : python-tempita-0.5.1-6.el7.noarch                                                                                                                               2/9
  Installing : python-paste-1.7.5.1-9.20111221hg1498.el7.noarch                                                                                                                3/9
  Installing : python-beaker-1.5.4-10.el7.noarch                                                                                                                               4/9
  Installing : python-markupsafe-0.11-10.el7.x86_64                                                                                                                            5/9
  Installing : python-mako-0.8.1-2.el7.noarch                                                                                                                                  6/9
  Installing : python-alembic-0.8.3-3.el7.noarch                                                                                                                               7/9
  Updating   : temboard-6.0-1.el7.noarch                                                                                                                                       8/9
  Cleanup    : temboard-5.1-1.el7.noarch                                                                                                                                       9/9
Uploading Package Profile
Loaded plugins: langpacks, product-id, subscription-manager
  Verifying  : python-alembic-0.8.3-3.el7.noarch                                                                                                                               1/9
  Verifying  : temboard-6.0-1.el7.noarch                                                                                                                                       2/9
  Verifying  : python-mako-0.8.1-2.el7.noarch                                                                                                                                  3/9
  Verifying  : python-markupsafe-0.11-10.el7.x86_64                                                                                                                            4/9
  Verifying  : python-tempita-0.5.1-6.el7.noarch                                                                                                                               5/9
  Verifying  : python-paste-1.7.5.1-9.20111221hg1498.el7.noarch                                                                                                                6/9
  Verifying  : python-beaker-1.5.4-10.el7.noarch                                                                                                                               7/9
  Verifying  : python-editor-0.4-4.el7.noarch                                                                                                                                  8/9
  Verifying  : temboard-5.1-1.el7.noarch                                                                                                                                       9/9

Dependency Installed:
  python-alembic.noarch 0:0.8.3-3.el7        python-beaker.noarch 0:1.5.4-10.el7                    python-editor.noarch 0:0.4-4.el7        python-mako.noarch 0:0.8.1-2.el7
  python-markupsafe.x86_64 0:0.11-10.el7     python-paste.noarch 0:1.7.5.1-9.20111221hg1498.el7     python-tempita.noarch 0:0.5.1-6.el7

Updated:
  temboard.noarch 0:6.0-1.el7

Complete!
Uploading Enabled Repositories Report
Loaded plugins: langpacks, product-id, subscription-manager

**Comment by bersace** [comment] 2020-06-15 12:32
Hi @wsescu thanks for the quick report ! A bugfix release 6.1 (for UI only) is available. Can you test it ?

**Comment by wsescu** [comment] 2020-06-15 12:33
Thank you very much. Will test it immediately.

**Comment by wsescu** [comment] 2020-06-15 12:44
Thanks @bersace 

After upgrading to Version 6.1, it works perfectly. 

Thank you very much for the quick fix.

**Comment by bersace** [comment] 2020-06-15 12:45
Thanks for the quick feedback ! @wsescu . Closing :-)

**Closed by bersace** 2020-06-15 12:45 UTC
